INFO: "test_challenge" выполнен успешно: 2024-11-05 11:58:57,597
WARNING: Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int: 2024-11-05 11:58:57,597
WARNING: Traceback (most recent call last):
  File "d:\Python\pythonProject\tests_12_4.py", line 81, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "d:\Python\pythonProject\tests_12_4.py", line 19, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {
TypeError: Имя может быть только строкой, передано int
: 2024-11-05 11:58:57,597
WARNING: Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5: 2024-11-05 11:58:57,597
WARNING: Traceback (most recent call last):
  File "d:\Python\pythonProject\tests_12_4.py", line 70, in test_walk
    runner = Runner("Nikolay", -5)
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Python\pythonProject\tests_12_4.py", line 25, in __init__
    raise ValueError(
ValueError: Скорость не может быть отрицательной, сейчас -5
: 2024-11-05 11:58:57,600
